CeruleanCity_House3_Text_PleaseTradeWithMyHusband::
    .string "My husband likes trading Pokémon.\p"
    .string "You're collecting Pokémon for your\n"
    .string "Pokédex, aren't you?\p"
    .string "Would you please trade with him?$"

CeruleanCity_House3_Text_TradeEvolution::
    .string "Did you know that some Pokémon only\n"
    .string "evolve through trading?\p"
    .string "If you could show me one of these\n"
    .string "Pokémon, I'll give you something\l"
    .string "that'll be useful for your journey.\p"
    .string "Do you have such a Pokémon with\n"
    .string "you?$"

CeruleanCity_House3_Text_ComeBack::
    .string "Feel free to talk to me when you\n"
    .string "have a Pokémon like that.$"

CeruleanCity_House3_Text_HereYouGo::
    .string "I'm certain that this Pokémon can\n"
    .string "evolve through trading.\p"
    .string "Here, please take it!$"

CeruleanCity_House3_Text_ExplainLinkingCord::
    .string "A Linking Cord is used to make\n"
    .string "certain species of Pokémon evolve.\p"
    .string "Think of it as an Evolution Stone,\n"
    .string "but specifically for trade evolutions.$"
